#!/bin/bash

#Scripts and Functions
    #ADD STARTUP FUNCTION
    startup_file="$HOME/.config/autostart/notification-box.desktop";
    if [ "$CHECKBOX_STARTUP" = "true" ]; then
        echo "[Desktop Entry]
                Version=0.03
                Type=Application
                Name=Notification Box
                Comment=This is a awesome notification app
                Icon=$BASE/icons/app-icon.png
                Exec=notification-box
                StartupNotify=false
                Terminal=false
                Categories=Utility;" > $startup_file;
    else
        if [[ -f $startup_file ]]; then
            rm $startup_file
        fi
    fi

    #UPTIME IS BIGGER THAN 30 SECONDS
    #uptime=$(cat /proc/uptime | grep -o '^[0-9]\+')
    #if [ "$uptime" -gt 30 ]; then
    #    export sys_uptime="1";
    #else
    #    export sys_uptime="0";
    #fi
    

    #GMAIL FUNCTION
    if [ "$CHECKBOX_GMAIL" = "true" ]; then
        [ -z "$(pgrep gmail.sh)" ] && $BASE/moduls/gmail.sh &
    else
        [ ! -z "$(pgrep gmail.sh)" ] && killall gmail.sh
    fi

    #FACEBOOK FUNCTION
    if [ "$CHECKBOX_FACEBOOK" = "true" ]; then
        [ -z "$(pgrep facebook.sh)" ] && $BASE/moduls/facebook.sh &
    else
        [ ! -z "$(pgrep facebook.sh)" ] && killall facebook.sh
    fi

    #WORDPRESS FUNCTION
    if [ "$CHECKBOX_WORDPRESS" = "true" ]; then
        [ -z "$(pgrep wordpress.sh)" ] && $BASE/moduls/wordpress.sh &
    else
        [ ! -z "$(pgrep wordpress.sh)" ] && killall wordpress.sh
    fi