#!/bin/bash

#Scripts and Functions

    #Getting scripts config informations
    function get_data (){
        informations=$(cat $BASE/moduls/$1);
        I=$IFS; IFS="" 
        for STATEMENTS in $informations; do 
           eval $STATEMENTS 
        done 
        IFS=$I
    }

    #Startup Gui
    function kill_start_without_gui (){
        [ ! -z "$(pgrep startup.sh)" ] && killall startup.sh
    }



    #Define the conditions
    run_scripts () {


        #ADD STARTUP FUNCTION
        startup_file="$HOME/.config/autostart/notification-box.desktop";
        if [ "$CHECKBOX_STARTUP" = "true" ] && [ "$CHECKBOX_HIDEGUI" = "false" ]; then
            echo "[Desktop Entry]
                    Version=0.1
                    Type=Application
                    Name=Notification Box
                    Comment=This is a awesome notification app
                    Icon=$BASE/icons/app-icon.png
                    Exec=$BASE/notification-box
                    StartupNotify=false
                    Terminal=false
                    Categories=Utility;" > $startup_file;
        elif [ "$CHECKBOX_STARTUP" = "true" ] && [ "$CHECKBOX_HIDEGUI" = "true" ]; then
                    echo "[Desktop Entry]
                    Version=0.1
                    Type=Application
                    Name=Notification Box
                    Comment=This is a awesome notification app
                    Icon=$BASE/icons/app-icon.png
                    Exec=$BASE/startup.sh
                    StartupNotify=false
                    Terminal=false
                    Categories=Utility;" > $startup_file;
        elif [ "$CHECKBOX_STARTUP" = "false" ] && [ "$CHECKBOX_HIDEGUI" = "false" ]; then
            if [ -f $startup_file ]; then
                rm $startup_file
            fi
        fi

        #GMAIL FUNCTION
        if [ "$CHECKBOX_GMAIL" = "true" ]; then
            [ -z "$(pgrep gmail.sh)" ] && $BASE/moduls/gmail.sh &
        else
            [ ! -z "$(pgrep gmail.sh)" ] && killall gmail.sh
        fi

        #FACEBOOK FUNCTION
        if [ "$CHECKBOX_FACEBOOK" = "true" ]; then
            [ -z "$(pgrep facebook.sh)" ] && $BASE/moduls/facebook.sh &
        else
            [ ! -z "$(pgrep facebook.sh)" ] && killall facebook.sh
        fi

        #WORDPRESS FUNCTION
        if [ "$CHECKBOX_WORDPRESS" = "true" ]; then
            [ -z "$(pgrep wordpress.sh)" ] && $BASE/moduls/wordpress.sh &
        else
            [ ! -z "$(pgrep wordpress.sh)" ] && killall wordpress.sh
        fi


    }